# Generated by Django 3.2 on 2021-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pre_registration_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tg', models.IntegerField(verbose_name='ID телеграм пользователя')),
                ('name', models.TextField(max_length=24, verbose_name='Имя')),
                ('surname', models.TextField(max_length=24, verbose_name='Фамилия')),
                ('email', models.TextField(verbose_name='EMAIL')),
                ('company', models.TextField(verbose_name='Компания')),
                ('position', models.TextField(verbose_name='Должность')),
                ('number', models.TextField(verbose_name='Номер телефона')),
                ('data_processing', models.TextField(verbose_name='Согласия на обработку данных')),
                ('status_user', models.TextField(max_length=24, verbose_name='Статус аккаунта пользователя')),
            ],
            options={
                'verbose_name': 'Аккаунты',
            },
        ),
    ]
