# Generated by Django 3.2 on 2021-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Названия компании')),
                ('INN', models.TextField(verbose_name='ИНН')),
                ('KPP', models.TextField(verbose_name='КПП')),
                ('OGRN', models.TextField(verbose_name='ОГРН')),
                ('adress', models.TextField(verbose_name='Юр.Адрес')),
                ('Mailing_address', models.TextField(verbose_name='Почтовый адрес')),
                ('FIO_director', models.TextField(verbose_name='ФИО Директора')),
                ('email', models.TextField(verbose_name='EMAIL')),
                ('id_tg', models.TextField(verbose_name='Телеграмм аккаунт')),
                ('number', models.TextField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='pre_registration_data',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
