# Generated by Django 3.2 on 2021-04-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20210430_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_registration_data',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adm.organization', verbose_name='Компания'),
        ),
    ]
