# Generated by Django 3.2 on 2021-04-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_pre_registration_data_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_registration_data',
            name='company',
            field=models.TextField(verbose_name='Компания'),
        ),
    ]
