# Generated by Django 3.2 on 2021-04-30 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_alter_pre_registration_data_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tg', models.TextField(verbose_name='ID телеграмма')),
                ('FIO', models.TextField(verbose_name='ФИО админа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.organization', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Админ группы',
                'verbose_name_plural': 'Админы группы',
            },
        ),
    ]
