# Generated by Django 3.2 on 2021-05-01 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_admin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_profile',
            name='rang',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Уровень администратора(1,2)'),
            preserve_default=False,
        ),
    ]
