# Generated by Django 3.2 on 2021-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_admin_profile_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_registration_data',
            name='login_bitrix',
            field=models.TextField(default=0, verbose_name='Логин пользователя в BitRix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_registration_data',
            name='password_bitrix',
            field=models.TextField(default=0, verbose_name='Пароль пользователя в Bitrix'),
            preserve_default=False,
        ),
    ]
