# Generated by Django 3.2 on 2021-05-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_logging_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging_message',
            name='date',
            field=models.DateField(verbose_name='Дата отправки сообщения'),
        ),
    ]
