# Generated by Django 3.2 on 2021-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_alter_logging_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging_message',
            name='name_user',
            field=models.TextField(default=0, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
