# Generated by Django 3.2 on 2021-05-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_logging_message_name_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='support_messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_anket', models.TextField(verbose_name='Номер заявки')),
                ('id_user', models.TextField(verbose_name='ID пользователя')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
    ]
