# Generated by Django 3.2 on 2021-05-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_support_messenger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_messenger',
            name='id_admin',
            field=models.TextField(default=0, verbose_name='ID админа обрабатывающего заявку'),
            preserve_default=False,
        ),
    ]
